In [2]:
import pandas as pd
df=pd.read_csv('carprices.csv')

In [3]:
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [4]:
new_col=pd.get_dummies(df['Car Model'])

In [5]:
comb_col=pd.concat([df,new_col],axis='columns')

In [6]:
comb_col

,Car Model,Mileage,Sell Price($),Age(yrs),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [7]:
new_df=comb_col.drop(['Car Model','Mercedez Benz C class'],axis='columns')
new_df

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6    False    True
1     35000          34000         3    False    True
2     57000          26100         5    False    True
3     22500          40000         2    False    True
4     46000          31500         4    False    True
5     59000          29400         5     True   False
6     52000          32000         5     True   False
7     72000          19300         6     True   False
8     91000          12000         8     True   False
9     67000          22000         6    False   False
10    83000          20000         7    False   False
11    79000          21000         7    False   False
12    59000          33000         5    False   False

In [8]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [9]:
X=new_df.drop(['Sell Price($)'],axis='columns')
X

    Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6    False    True
1     35000         3    False    True
2     57000         5    False    True
3     22500         2    False    True
4     46000         4    False    True
5     59000         5     True   False
6     52000         5     True   False
7     72000         6     True   False
8     91000         8     True   False
9     67000         6    False   False
10    83000         7    False   False
11    79000         7    False   False
12    59000         5    False   False

In [10]:
y=new_df['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [11]:
lr.fit(X,y)

LinearRegression()

In [22]:
lr.predict([[25000,7,False,True]])

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([33658.19088988])

In [23]:
lr.score(X,y)

0.9417050937281083

In [24]:
# ONE HOT ENCODING

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [29]:
df_le=df
df_le['Car Model']=le.fit_transform(df_le['Car Model'])

In [30]:
df_le

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [78]:
X=df_le[['Car Model','Mileage','Age(yrs)']].values
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]])

In [95]:
y=df_le['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [96]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

# Example training data
X = np.array([
    ['red', 2000],
    ['blue', 1500],
    ['green', 2500],
    ['yellow', 3000]
])
y = np.array([500000, 350000, 450000, 600000])

# Fit OneHotEncoder on categorical column
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_cat = ohe.fit_transform(X[:, [0]])  # only first column

# Combine with numeric columns
X_final = np.concatenate([X_cat, X[:, 1:].astype(float)], axis=1)

# Fit model
lr = LinearRegression()
lr.fit(X_final, y)

# New sample to predict
new_sample = np.array([['blue', 2800]])  # raw input

# Transform categorical column
new_cat = ohe.transform(new_sample[:, [0]])
new_num = new_sample[:, 1:].astype(float)

# Combine transformed data
new_final = np.concatenate([new_cat, new_num], axis=1)

# Predict
prediction = lr.predict(new_final)
print(prediction)

[554285.65591847]