In [1]:
import pandas as pd
df=pd.read_csv('salaries.csv')
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [4]:
inputs=df.iloc[:,:-1]
inputs

       company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [5]:
output=df.iloc[:,-1]
output

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [6]:
df

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [7]:
from sklearn.preprocessing import LabelEncoder
company_le=LabelEncoder()
job_le=LabelEncoder()
degree_le=LabelEncoder()
df['new_company']=company_le.fit_transform(df['company'])
df['new_job']=job_le.fit_transform(df['job'])
df['new_degree']=degree_le.fit_transform(df['company'])

In [8]:
df

,company,job,degree,salary_more_then_100k,new_company,new_job,new_degree
0,google,sales executive,bachelors,0,2,2,2
1,google,sales executive,masters,0,2,2,2
2,google,business manager,bachelors,1,2,0,2
3,google,business manager,masters,1,2,0,2
4,google,computer programmer,bachelors,0,2,1,2
5,google,computer programmer,masters,1,2,1,2
6,abc pharma,sales executive,masters,0,0,2,0
7,abc pharma,computer programmer,bachelors,0,0,1,0
8,abc pharma,business manager,bachelors,0,0,0,0
9,abc pharma,business manager,masters,1,0,0,0
10,facebook,sales executive,bachelors,1,1,2,1
11,facebook,sales executive,masters,1,1,2,1
12,facebook,business manager,bachelors,1,1,0,1
13,facebook,business manager,masters,1,1,0,1
14,facebook,computer programmer,bachelors,1,1,1,1
15,facebook,computer programmer,masters,1,1,1,1

In [10]:
df=df.drop(['company','job','degree'],axis='columns')
df

    salary_more_then_100k  new_company  new_job  new_degree
0                       0            2        2           2
1                       0            2        2           2
2                       1            2        0           2
3                       1            2        0           2
4                       0            2        1           2
5                       1            2        1           2
6                       0            0        2           0
7                       0            0        1           0
8                       0            0        0           0
9                       1            0        0           0
10                      1            1        2           1
11                      1            1        2           1
12                      1            1        0           1
13                      1            1        0           1
14                      1            1        1           1
15                      1            1        1           1

In [13]:
new_inputs=df[['new_company','new_job','new_degree']]
new_inputs

    new_company  new_job  new_degree
0             2        2           2
1             2        2           2
2             2        0           2
3             2        0           2
4             2        1           2
5             2        1           2
6             0        2           0
7             0        1           0
8             0        0           0
9             0        0           0
10            1        2           1
11            1        2           1
12            1        0           1
13            1        0           1
14            1        1           1
15            1        1           1

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(new_inputs,output,test_size=0.2)

In [16]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [18]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [20]:
model.predict(X_test)

array([1, 1, 1, 0])

In [21]:
model.score(X_test,y_test)

0.75

In [23]:
model.predict([[1,2,1]])

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])